# Generated by Django 4.2.13 on 2024-06-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзывы/Reviews', 'verbose_name_plural': 'Отзывы/Reviews'},
        ),
    ]
