# Generated by Django 4.2.13 on 2024-06-05 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Клиенты/Clients', 'verbose_name_plural': 'Клиенты/Clients'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Врачи/Doctor', 'verbose_name_plural': 'Врачи/Doctor'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ/Order', 'verbose_name_plural': 'Заказ/Order'},
        ),
        migrations.AlterModelOptions(
            name='pets',
            options={'verbose_name': 'Питомцы/Pets', 'verbose_name_plural': 'Питомцы/Pets'},
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'verbose_name': 'Процедуры/Procedure', 'verbose_name_plural': 'Процедуры/Procedure'},
        ),
        migrations.AlterModelOptions(
            name='vacations',
            options={'verbose_name': 'Отпуска/Vacations', 'verbose_name_plural': 'Отпуска/Vacations'},
        ),
        migrations.AddField(
            model_name='order',
            name='time_order',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время бронирования'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(verbose_name='Дата бронирования'),
        ),
    ]
