# Generated by Django 4.2.13 on 2024-06-08 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='procedure',
        ),
        migrations.AddField(
            model_name='doctor',
            name='order',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='service.order'),
            preserve_default=False,
        ),
    ]
