# Generated by Django 4.2.13 on 2024-06-08 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_doctor_procedure_doctor_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='doctor',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='service.doctor'),
            preserve_default=False,
        ),
    ]
