# Generated by Django 4.2.13 on 2024-06-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_doctor_order_order_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateField(verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_order',
            field=models.TimeField(verbose_name='Время бронирования'),
        ),
    ]
